[phases.setup]
nixPkgs = [
    "nodejs",
    "python3",
    "python3Packages.pip",
    "python3Packages.virtualenv"
]

[phases.install]
cmds = [
    "npm install",
    "python3 -m venv venv",
    "source venv/bin/activate && pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "source venv/bin/activate && npm start" 