[phases.setup]
nixPkgs = [
    "nodejs-20_x",
    "python310",
    "python310Packages.pip",
    "python310Packages.virtualenv"
]

[phases.install]
cmds = [
    "npm install"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "source venv/bin/activate && npm start" 