[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "source venv/bin/activate && node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases]
setup = [
    "nodejs",
    "python3",
    "python3Packages.pip",
    "python3Packages.virtualenv"
] 