[build]
builder = "nixpacks"
buildCommand = "./build.sh"

[deploy]
startCommand = "source venv/bin/activate && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases]
setup = [
    "nodejs",
    "python3",
    "python3Packages.pip",
    "python3Packages.virtualenv"
] 