[build]
builder = "nixpacks"
buildCommand = "./build.sh"

[deploy]
startCommand = "source venv/bin/activate && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases]
setup = [
    "nodejs-20_x",
    "python310",
    "python310Packages.pip",
    "python310Packages.virtualenv"
] 