[build]
builder = "DOCKERFILE"
dockerfilePath = "./backend/Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 30
healthcheckStartPeriod = 5
healthcheckRetries = 3
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 